on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0
      - run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  docker:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker build -t owensweet/personal-site:latest .
          docker push owensweet/personal-site:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_PEM }}
          port: 22
          script: |
            # Install Docker and compose plugin if missing
            if ! command -v docker &> /dev/null; then
              sudo dnf install -y docker docker-compose-plugin
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker ec2-user
            fi

            # Go to home and clone/update repo
            cd /home/ec2-user
            if [ ! -d personal-site ]; then
              git clone https://github.com/owensweet/personal-site.git
            else
              cd personal-site
              git pull
            fi
            cd personal-site

            # Run Docker Compose (plugin version)
            docker compose pull
            docker compose up -d --remove-orphans
            docker system prune -f


